name: Rifaya Apps CI/CD

on:
  pull_request:
    types:
      - closed  # Hanya berjalan saat merge ke main
    branches:
      - main  # Ubah sesuai branch utama Anda

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Dependencies
        run: |
          composer install --no-dev --prefer-dist

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}

        run: |
          echo "Installing SSH Client..."
          sudo apt-get install -y openssh-client

          echo "Setting up SSH..."
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 65002 $SSH_HOST >> ~/.ssh/known_hosts

          echo "Connecting to server and deploying..."
          ssh -o StrictHostKeyChecking=no -p 65002 $SSH_USER@$SSH_HOST 'bash -s' << 'EOF'
          set -e
          echo "Deploying on server..."
          cd /home/u504186664/domains/rifayaeducation.com/public_html
          git pull origin main
          composer install --ignore-platform-reqs
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          echo "Deployment successful!" >> deploy.log
          EOF